### ISSUE TITLE
Curious.. interested in converting source to Org?

### ISSUE THREAD

**Issue by kaushalmodi** [btbytes/nim-cookbook#14]
Hello,

I am interested in learning Nim, and that's how I came across this cookbook. 

I also use Emacs/Org, and glancing through your repos, you probably also use, or at least know about Org? :)

If so, I was curious if you had thought of writing the source of this site in Org (+Babel) instead of Markdown. 

Example:

- [Org source][1]
- [Rendered site with code + results][2]

WDYT?

[1]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/raw/master/content-org/notes/string-fns-nim-vs-python.org

[2]: https://scripter.co/notes/string-functions-nim-vs-python/

**Comment by ghost** [comment]
@kaushalmodi ORG syntax looks a lot harder to understand, also it's not as widespread as Markdown.
sorry, but -1 from me :)

**Comment by btbytes** [comment]
@kaushalmodi [I like Org-mode!](https://www.btbytes.com/pages/org-simple.html) I  However,  markdown is easy to contribute to for the wider community.  Sorry.
