### ISSUE TITLE
Please add a recipe for a garbage-collected shared mem

### ISSUE THREAD

**Issue by wizzardx** [btbytes/nim-cookbook#15]
From over here in the Nim forum:
https://forum.nim-lang.org/t/2457/2
In the post from mratsim at 2017-10-26 19:19:16

**Comment by btbytes** [comment]
Hi @wizzardx if you can write "What the $problem is " and how this code solves that $problem, I can look into adding it to the recipes. I was not able to come up with a good explanation for this.
